# https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#templating-with-jinja

{% set data = load_setup_py_data() %}

package:
  name: control
  version: {{ data.get('version') }}

build:
  script:
    - cd $RECIPE_DIR/..
    - $PYTHON make_version.py
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ python }}
    - nose

  run:
    - python {{ python }}
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - control

about:
  home: http://python-control.sourceforge.net
  license:  BSD License
  summary: 'Python control systems library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

# Also see
# https://conda.io/docs/user-guide/tasks/build-packages/variants.html for
# updates after conda_build > 3.0
