import os
import unittest

import fortran_to_python_easy as f2pe


class TestFortranToPythonEasy(unittest.TestCase):
    def setUp(self):
        self.filename = os.path.join(os.pardir, 'pyslicot', 'SB02MT.f')

    def test_is_comment(self):
        test_cases = {('      SUBROUTINE SB02MT( JOBG, JOBL, FACT, UPLO, N, M, A, LDA, B, LDB,', False),
                      ('     $                   Q, LDQ, R, LDR, L, LDL, IPIV, OUFACT, G, LDG,', False),
                      ('     $                   IWORK, DWORK, LDWORK, INFO )', False),
                      ('C', True),
                      ('C     SLICOT RELEASE 5.0.', True),
                      ('C', True),
                      ('C     Copyright (c) 2002-2009 NICONET e.V.', True),
                      ('C', True),
                      ('C     This program is free software: you can redistribute it and/or', True),
                      ('C     modify it under the terms of the GNU General Public License as', True),
                      ('C     published by the Free Software Foundation, either version 2 of', True),
                      ('C     the License, or (at your option) any later version.', True),
                      ('C', True),
                      ('C     This program is distributed in the hope that it will be useful,', True),
                      ('C     but WITHOUT ANY WARRANTY; without even the implied warranty of', True),
                      ('C     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the', True),
                      ('C     GNU General Public License for more details.', True),
                      ('C', True),
                      ('C     You should have received a copy of the GNU General Public License', True),
                      ('C     along with this program.  If not, see', True),
                      ('C     <http://www.gnu.org/licenses/>.', True),
                      ('C', True),
                      ('C     PURPOSE', True),
                      ('C', True),
                      ('C     To compute the following matrices', True),
                      ('C', True),
                      ('C                -1', True),
                      ("C         G = B*R  *B',", True),
                      ('C', True),
                      ('C         -          -1', True),
                      ("C         A = A - B*R  *L',", True),
                      ('C', True),
                      ('C         -          -1', True),
                      ("C         Q = Q - L*R  *L',", True),
                      ('C', True),
                      ('C     where A, B, Q, R, L, and G are N-by-N, N-by-M, N-by-N, M-by-M,', True),
                      ('C     N-by-M, and N-by-N matrices, respectively, with Q, R and G', True),
                      ('C     symmetric matrices.', True),
                      ('C', True),
                      ('C     When R is well-conditioned with respect to inversion, standard', True),
                      ('C     algorithms for solving linear-quadratic optimization problems will', True),
                      ('C     then also solve optimization problems with coupling weighting', True),
                      ('C     matrix L. Moreover, a gain in efficiency is possible using matrix', True),
                      ('C     G in the deflating subspace algorithms (see SLICOT Library routine', True),
                      ('C     SB02OD).', True),
                      ('C', True),
                      ('C     ARGUMENTS', True),
                      ('C', True),
                      ('C     Mode Parameters', True),
                      ('C', True),
                      ('C     JOBG    CHARACTER*1', True),
                      ('C             Specifies whether or not the matrix G is to be computed,', True),
                      ('C             as follows:', True),
                      ("C             = 'G':  Compute G;", True),
                      ("C             = 'N':  Do not compute G.", True),
                      ('C', True),
                      ('C     JOBL    CHARACTER*1', True),
                      ('C             Specifies whether or not the matrix L is zero, as follows:', True),
                      ("C             = 'Z':  L is zero;", True),
                      ("C             = 'N':  L is nonzero.", True),
                      ('C', True),
                      ('C     FACT    CHARACTER*1', True),
                      ('C             Specifies how the matrix R is given (factored or not), as', True),
                      ('C             follows:', True),
                      ("C             = 'N':  Array R contains the matrix R;", True),
                      ("C             = 'C':  Array R contains the Cholesky factor of R;", True),
                      ("C             = 'U':  Array R contains the symmetric indefinite UdU' or", True),
                      ("C                     LdL' factorization of R.", True),
                      ('C', True),
                      ('C     UPLO    CHARACTER*1', True),
                      ('C             Specifies which triangle of the matrices R and Q (if', True),
                      ("C             JOBL = 'N') is stored, as follows:", True),
                      ("C             = 'U':  Upper triangle is stored;", True),
                      ("C             = 'L':  Lower triangle is stored.", True),
                      ('C', True),
                      ('C     Input/Output Parameters', True),
                      ('C', True),
                      ('C     N       (input) INTEGER', True),
                      ('C             The order of the matrices A, Q, and G, and the number of', True),
                      ('C             rows of the matrices B and L.  N >= 0.', True),
                      ('C', True),
                      ('C     M       (input) INTEGER', True),
                      ('C             The order of the matrix R, and the number of columns of', True),
                      ('C             the matrices B and L.  M >= 0.', True),
                      ('C', True),
                      ('C     A       (input/output) DOUBLE PRECISION array, dimension (LDA,N)', True),
                      ("C             On entry, if JOBL = 'N', the leading N-by-N part of this", True),
                      ('C             array must contain the matrix A.', True),
                      ("C             On exit, if JOBL = 'N', and INFO = 0, the leading N-by-N", True),
                      ('C                                                    -          -1', True),
                      ("C             part of this array contains the matrix A = A - B*R  L'.", True),
                      ("C             If JOBL = 'Z', this array is not referenced.", True),
                      ('C', True),
                      ('C     LDA     INTEGER', True),
                      ('C             The leading dimension of array A.', True),
                      ("C             LDA >= MAX(1,N) if JOBL = 'N';", True),
                      ("C             LDA >= 1        if JOBL = 'Z'.", True),
                      ('C', True),
                      ('C     B       (input/output) DOUBLE PRECISION array, dimension (LDB,M)', True),
                      ('C             On entry, the leading N-by-M part of this array must', True),
                      ('C             contain the matrix B.', True),
                      ('C             On exit, if OUFACT = 1, and INFO = 0, the leading N-by-M', True),
                      ('C                                                             -1', True),
                      ('C             part of this array contains the matrix B*chol(R)  .', True),
                      ('C             On exit, B is unchanged if OUFACT = 2 (hence also when', True),
                      ("C             FACT = 'U').", True),
                      ('C', True),
                      ('C     LDB     INTEGER', True),
                      ('C             The leading dimension of array B.  LDB >= MAX(1,N).', True),
                      ('C', True),
                      ('C     Q       (input/output) DOUBLE PRECISION array, dimension (LDQ,N)', True),
                      ("C             On entry, if JOBL = 'N', the leading N-by-N upper", True),
                      ("C             triangular part (if UPLO = 'U') or lower triangular part", True),
                      ("C             (if UPLO = 'L') of this array must contain the upper", True),
                      ('C             triangular part or lower triangular part, respectively, of', True),
                      ('C             the symmetric matrix Q. The stricly lower triangular part', True),
                      ("C             (if UPLO = 'U') or stricly upper triangular part (if", True),
                      ("C             UPLO = 'L') is not referenced.", True),
                      ("C             On exit, if JOBL = 'N' and INFO = 0, the leading N-by-N", True),
                      ("C             upper triangular part (if UPLO = 'U') or lower triangular", True),
                      ("C             part (if UPLO = 'L') of this array contains the upper", True),
                      ('C             triangular part or lower triangular part, respectively, of', True),
                      ('C                                  -          -1', True),
                      ("C             the symmetric matrix Q = Q - L*R  *L'.", True),
                      ("C             If JOBL = 'Z', this array is not referenced.", True),
                      ('C', True),
                      ('C     LDQ     INTEGER', True),
                      ('C             The leading dimension of array Q.', True),
                      ("C             LDQ >= MAX(1,N) if JOBL = 'N';", True),
                      ("C             LDQ >= 1        if JOBL = 'Z'.", True),
                      ('C', True),
                      ('C     R       (input/output) DOUBLE PRECISION array, dimension (LDR,M)', True),
                      ("C             On entry, if FACT = 'N', the leading M-by-M upper", True),
                      ("C             triangular part (if UPLO = 'U') or lower triangular part", True),
                      ("C             (if UPLO = 'L') of this array must contain the upper", True),
                      ('C             triangular part or lower triangular part, respectively,', True),
                      ('C             of the symmetric input weighting matrix R.', True),
                      ("C             On entry, if FACT = 'C', the leading M-by-M upper", True),
                      ("C             triangular part (if UPLO = 'U') or lower triangular part", True),
                      ("C             (if UPLO = 'L') of this array must contain the Cholesky", True),
                      ('C             factor of the positive definite input weighting matrix R', True),
                      ('C             (as produced by LAPACK routine DPOTRF).', True),
                      ("C             On entry, if FACT = 'U', the leading M-by-M upper", True),
                      ("C             triangular part (if UPLO = 'U') or lower triangular part", True),
                      ("C             (if UPLO = 'L') of this array must contain the factors of", True),
                      ("C             the UdU' or LdL' factorization, respectively, of the", True),
                      ('C             symmetric indefinite input weighting matrix R (as produced', True),
                      ('C             by LAPACK routine DSYTRF).', True),
                      ("C             If FACT = 'N', the stricly lower triangular part (if UPLO", True),
                      ("C             = 'U') or stricly upper triangular part (if UPLO = 'L') of", True),
                      ('C             this array is used as workspace.', True),
                      ('C             On exit, if OUFACT = 1, and INFO = 0 (or INFO = M+1),', True),
                      ("C             the leading M-by-M upper triangular part (if UPLO = 'U')", True),
                      ("C             or lower triangular part (if UPLO = 'L') of this array", True),
                      ('C             contains the Cholesky factor of the given input weighting', True),
                      ('C             matrix.', True),
                      ('C             On exit, if OUFACT = 2, and INFO = 0 (or INFO = M+1),', True),
                      ("C             the leading M-by-M upper triangular part (if UPLO = 'U')", True),
                      ("C             or lower triangular part (if UPLO = 'L') of this array", True),
                      ("C             contains the factors of the UdU' or LdL' factorization,", True),
                      ('C             respectively, of the given input weighting matrix.', True),
                      ("C             On exit R is unchanged if FACT = 'C' or 'U'.", True),
                      ('C', True),
                      ('C     LDR     INTEGER', True),
                      ('C             The leading dimension of array R.  LDR >= MAX(1,M).', True),
                      ('C', True),
                      ('C     L       (input/output) DOUBLE PRECISION array, dimension (LDL,M)', True),
                      ("C             On entry, if JOBL = 'N', the leading N-by-M part of this", True),
                      ('C             array must contain the matrix L.', True),
                      ("C             On exit, if JOBL = 'N', OUFACT = 1, and INFO = 0, the", True),
                      ('C             leading N-by-M part of this array contains the matrix', True),
                      ('C                      -1', True),
                      ('C             L*chol(R)  .', True),
                      ('C             On exit, L is unchanged if OUFACT = 2 (hence also when', True),
                      ("C             FACT = 'U').", True),
                      ("C             L is not referenced if JOBL = 'Z'.", True),
                      ('C', True),
                      ('C     LDL     INTEGER', True),
                      ('C             The leading dimension of array L.', True),
                      ("C             LDL >= MAX(1,N) if JOBL = 'N';", True),
                      ("C             LDL >= 1        if JOBL = 'Z'.", True),
                      ('C', True),
                      ('C     IPIV    (input/output) INTEGER array, dimension (M)', True),
                      ("C             On entry, if FACT = 'U', this array must contain details", True),
                      ('C             of the interchanges performed and the block structure of', True),
                      ("C             the d factor in the UdU' or LdL' factorization of matrix R", True),
                      ('C             (as produced by LAPACK routine DSYTRF).', True),
                      ('C             On exit, if OUFACT = 2, this array contains details of', True),
                      ('C             the interchanges performed and the block structure of the', True),
                      ("C             d factor in the UdU' or LdL' factorization of matrix R,", True),
                      ('C             as produced by LAPACK routine DSYTRF.', True),
                      ("C             This array is not referenced if FACT = 'C'.", True),
                      ('C', True),
                      ('C     OUFACT  (output) INTEGER', True),
                      ('C             Information about the factorization finally used.', True),
                      ('C             OUFACT = 1:  Cholesky factorization of R has been used;', True),
                      ("C             OUFACT = 2:  UdU' (if UPLO = 'U') or LdL' (if UPLO = 'L')", True),
                      ('C                          factorization of R has been used.', True),
                      ('C', True),
                      ('C     G       (output) DOUBLE PRECISION array, dimension (LDG,N)', True),
                      ("C             If JOBG = 'G', and INFO = 0, the leading N-by-N upper", True),
                      ("C             triangular part (if UPLO = 'U') or lower triangular part", True),
                      ("C             (if UPLO = 'L') of this array contains the upper", True),
                      ("C             triangular part (if UPLO = 'U') or lower triangular part", True),
                      ('C                                                                 -1', True),
                      ("C             (if UPLO = 'L'), respectively, of the matrix G = B*R  B'.", True),
                      ("C             If JOBG = 'N', this array is not referenced.", True),
                      ('C', True),
                      ('C     LDG     INTEGER', True),
                      ('C             The leading dimension of array G.', True),
                      ("C             LDG >= MAX(1,N) if JOBG = 'G',", True),
                      ("C             LDG >= 1        if JOBG = 'N'.", True),
                      ('C', True),
                      ('C     Workspace', True),
                      ('C', True),
                      ('C     IWORK   INTEGER array, dimension (M)', True),
                      ('C', True),
                      ('C     DWORK   DOUBLE PRECISION array, dimension (LDWORK)', True),
                      ('C             On exit, if INFO = 0, DWORK(1) returns the optimal value', True),
                      ("C             of LDWORK; if FACT = 'N', DWORK(2) contains the reciprocal", True),
                      ('C             condition number of the given matrix R.', True),
                      ('C', True),
                      ('C     LDWORK  INTEGER', True),
                      ('C             The length of the array DWORK.', True),
                      ("C             LDWORK >= 1              if FACT = 'C';", True),
                      ("C             LDWORK >= MAX(2,3*M,N*M) if FACT = 'N';", True),
                      ("C             LDWORK >= MAX(1,N*M)     if FACT = 'U'.", True),
                      ('C             For optimum performance LDWORK should be larger than 3*M,', True),
                      ("C             if FACT = 'N'.", True),
                      ("C             The N*M workspace is not needed for FACT = 'N', if matrix", True),
                      ('C             R is positive definite.', True),
                      ('C', True),
                      ('C     Error Indicator', True),
                      ('C', True),
                      ('C     INFO    INTEGER', True),
                      ('C             = 0:  successful exit;', True),
                      ('C             < 0:  if INFO = -i, the i-th argument had an illegal', True),
                      ('C                   value;', True),
                      ('C             = i:  if the i-th element (1 <= i <= M) of the d factor is', True),
                      ("C                   exactly zero; the UdU' (or LdL') factorization has", True),
                      ('C                   been completed, but the block diagonal matrix d is', True),
                      ('C                   exactly singular;', True),
                      ('C             = M+1:  if the matrix R is numerically singular.', True),
                      ('C', True),
                      ('C     METHOD', True),
                      ('C                            -     -', True),
                      ('C     The matrices G, and/or A and Q are evaluated using the given or', True),
                      ('C     computed symmetric factorization of R.', True),
                      ('C', True),
                      ('C     NUMERICAL ASPECTS', True),
                      ('C', True),
                      ('C     The routine should not be used when R is ill-conditioned.', True),
                      ('C', True),
                      ('C     CONTRIBUTOR', True),
                      ('C', True),
                      ('C     Release 3.0: V. Sima, Katholieke Univ. Leuven, Belgium, Sep. 1997.', True),
                      ('C', True),
                      ('C     REVISIONS', True),
                      ('C', True),
                      ('C     -', True),
                      ('C', True),
                      ('C     KEYWORDS', True),
                      ('C', True),
                      ('C     Algebraic Riccati equation, closed loop system, continuous-time', True),
                      ('C     system, discrete-time system, optimal regulator, Schur form.', True),
                      ('C', True),
                      ('C     ******************************************************************', True),
                      ('"""', True),
                      ('C', True),
                      ('C     .. Parameters ..', True),
                      ('      DOUBLE PRECISION  ZERO, ONE', False),
                      ('      PARAMETER         ( ZERO = 0.0D0, ONE = 1.0D0 )', False),
                      ('C     .. Scalar Arguments ..', True),
                      ('      CHARACTER         FACT, JOBG, JOBL, UPLO', False),
                      ('      INTEGER           INFO, LDA, LDB, LDG, LDL, LDQ, LDR, LDWORK, M,', False),
                      ('     $                  N, OUFACT', False),
                      ('C     .. Array Arguments ..', True),
                      ('      INTEGER           IPIV(*), IWORK(*)', False),
                      ('      DOUBLE PRECISION  A(LDA,*), B(LDB,*), DWORK(*), G(LDG,*),', False),
                      ('     $                  L(LDL,*), Q(LDQ,*), R(LDR,*)', False),
                      ('C     .. Local Scalars ..', True),
                      ('      LOGICAL           LFACTA, LFACTC, LFACTU, LJOBG, LJOBL, LUPLOU', False),
                      ('      CHARACTER         TRANS', False),
                      ('      INTEGER           I, J, WRKOPT', False),
                      ('      DOUBLE PRECISION  EPS, RCOND, RNORM', False),
                      ('C     .. External Functions ..', True),
                      ('      LOGICAL           LSAME', False),
                      ('      DOUBLE PRECISION  DLAMCH, DLANSY', False),
                      ('      EXTERNAL          DLAMCH, DLANSY, LSAME', False),
                      ('C     .. External Subroutines ..', True),
                      ('      EXTERNAL          DCOPY, DGEMM, DGEMV, DPOCON, DPOTRF, DSYCON,', False),
                      ('     $                  DSYRK, DSYTRF, DSYTRS, DTRSM, XERBLA', False),
                      ('C     .. Intrinsic Functions ..', True),
                      ('      INTRINSIC         INT, MAX', False),
                      ('C     .. Executable Statements ..', True),
                      ('C', True),
                      ('      INFO   = 0', False),
                      ("      LJOBG  = LSAME( JOBG, 'G' )", False),
                      ("      LJOBL  = LSAME( JOBL, 'N' )", False),
                      ("      LFACTC = LSAME( FACT, 'C' )", False),
                      ("      LFACTU = LSAME( FACT, 'U' )", False),
                      ("      LUPLOU = LSAME( UPLO, 'U' )", False),
                      ('      LFACTA = LFACTC.OR.LFACTU', False),
                      ('C', True),
                      ('C     Test the input scalar arguments.', True),
                      ('C', True),
                      ("      IF( .NOT.LJOBG .AND. .NOT.LSAME( JOBG, 'N' ) ) THEN", False),
                      ('         INFO = -1', False),
                      ("      ELSE IF( .NOT.LJOBL .AND. .NOT.LSAME( JOBL, 'Z' ) ) THEN", False),
                      ('         INFO = -2', False),
                      ("      ELSE IF( .NOT.LFACTA .AND. .NOT.LSAME( FACT, 'N' ) ) THEN", False),
                      ('         INFO = -3', False),
                      ("      ELSE IF( .NOT.LUPLOU .AND. .NOT.LSAME( UPLO, 'L' ) ) THEN", False),
                      ('         INFO = -4', False),
                      ('      ELSE IF( N.LT.0 ) THEN', False),
                      ('         INFO = -5', False),
                      ('      ELSE IF( M.LT.0 ) THEN', False),
                      ('         INFO = -6', False),
                      ('      ELSE IF( ( LDA.LT.1 ) .OR. ( LJOBL .AND. LDA.LT.N ) ) THEN', False),
                      ('         INFO = -8', False),
                      ('      ELSE IF( LDB.LT.MAX( 1, N ) ) THEN', False),
                      ('         INFO = -10', False),
                      ('      ELSE IF( ( LDQ.LT.1 ) .OR. ( LJOBL .AND. LDQ.LT.N ) ) THEN', False),
                      ('         INFO = -12', False),
                      ('      ELSE IF( LDR.LT.MAX( 1, M ) ) THEN', False),
                      ('         INFO = -14', False),
                      ('      ELSE IF( ( LDL.LT.1 ) .OR. ( LJOBL .AND. LDL.LT.N ) ) THEN', False),
                      ('         INFO = -16', False),
                      ('      ELSE IF( ( LDG.LT.1 ) .OR. ( LJOBG .AND. LDG.LT.N ) ) THEN', False),
                      ('         INFO = -20', False),
                      ('      ELSE IF( ( LFACTC .AND. LDWORK.LT.1 ) .OR.', False),
                      ('     $         ( LFACTU .AND. LDWORK.LT.MAX( 1, N*M ) ) .OR.', False),
                      ('     $    ( .NOT.LFACTA .AND. LDWORK.LT.MAX( 2, N*M, 3*M ) ) ) THEN', False),
                      ('         INFO = -23', False),
                      ('      END IF', False),
                      ('C', True),
                      ('      IF ( INFO.NE.0 ) THEN', False),
                      ('C', True),
                      ('C        Error return.', True),
                      ('C', True),
                      ("         CALL XERBLA( 'sb02mt', -INFO )", False),
                      ('         RETURN', False),
                      ('      END IF', False),
                      ('C', True),
                      ('      IF ( LFACTC ) THEN', False),
                      ('         OUFACT = 1', False),
                      ('      ELSE IF ( LFACTU ) THEN', False),
                      ('         OUFACT = 2', False),
                      ('      END IF', False),
                      ('C', True),
                      ('C     Quick return if possible.', True),
                      ('C', True),
                      ('      IF ( N.EQ.0 .OR. M.EQ.0 .OR. .NOT.( LJOBL.OR.LJOBG ) ) THEN', False),
                      ('        DWORK(1) = ONE', False),
                      ('        IF ( .NOT.LFACTA ) DWORK(2) = ONE', False),
                      ('        RETURN', False),
                      ('      END IF', False),
                      ('C', True),
                      ('C     (Note: Comments in the code beginning "Workspace:" describe the', True),
                      ('C     minimal amount of workspace needed at that point in the code,', True),
                      ('C     as well as the preferred amount for good performance.', True),
                      ('C     NB refers to the optimal block size for the immediately', True),
                      ('C     following subroutine, as returned by ILAENV.)', True),
                      ('C', True),
                      ('      WRKOPT = 1', False),
                      ('C', True),
                      ('C     Set relative machine precision.', True),
                      ('C', True),
                      ("      EPS = DLAMCH( 'Epsilon' )", False),
                      ('C', True),
                      ('      IF ( .NOT.LFACTA ) THEN', False),
                      ('C', True),
                      ('C        Compute the norm of the matrix R, which is not factored.', True),
                      ('C        Then save the given triangle of R in the other strict triangle', True),
                      ('C        and the diagonal in the workspace, and try Cholesky', True),
                      ('C        factorization.', True),
                      ('C        Workspace: need M.', True),
                      ('C', True),
                      ("         RNORM = DLANSY( '1-norm', UPLO, M, R, LDR, DWORK )", False),
                      ('         CALL DCOPY( M, R, LDR+1, DWORK, 1 )', False),
                      ('         IF( LUPLOU ) THEN', False),
                      ('C', True),
                      ('            DO 20 J = 2, M', False),
                      ('               CALL DCOPY( J-1, R(1,J), 1, R(J,1), LDR )', False),
                      ('   20       CONTINUE', False),
                      ('C', True),
                      ('         ELSE', False),
                      ('C', True),
                      ('            DO 40 J = 2, M', False),
                      ('               CALL DCOPY( J-1, R(J,1), LDR, R(1,J), 1 )', False),
                      ('   40       CONTINUE', False),
                      ('C', True),
                      ('         END IF', False),
                      ('         CALL DPOTRF( UPLO, M, R, LDR, INFO )', False),
                      ('         IF( INFO.EQ.0 ) THEN', False),
                      ('C', True),
                      ('C           Compute the reciprocal of the condition number of R.', True),
                      ('C           Workspace: need 3*M.', True),
                      ('C', True),
                      ('            CALL DPOCON( UPLO, M, R, LDR, RNORM, RCOND, DWORK, IWORK,', False),
                      ('     $                   INFO )', False),
                      ('C', True),
                      ('C           Return if the matrix is singular to working precision.', True),
                      ('C', True),
                      ('            OUFACT = 1', False),
                      ('            DWORK(2) = RCOND', False),
                      ('            IF( RCOND.LT.EPS ) THEN', False),
                      ('               INFO = M + 1', False),
                      ('               RETURN', False),
                      ('            END IF', False),
                      ('            WRKOPT = MAX( WRKOPT, 3*M )', False),
                      ('         ELSE', False),
                      ('C', True),
                      ("C           Use UdU' or LdL' factorization, first restoring the saved", True),
                      ('C           triangle.', True),
                      ('C', True),
                      ('            CALL DCOPY( M, DWORK, 1, R, LDR+1 )', False),
                      ('            IF( LUPLOU ) THEN', False),
                      ('C', True),
                      ('               DO 60 J = 2, M', False),
                      ('                  CALL DCOPY( J-1, R(J,1), LDR, R(1,J), 1 )', False),
                      ('   60          CONTINUE', False),
                      ('C', True),
                      ('            ELSE', False),
                      ('C', True),
                      ('               DO 80 J = 2, M', False),
                      ('                  CALL DCOPY( J-1, R(1,J), 1, R(J,1), LDR )', False),
                      ('   80          CONTINUE', False),
                      ('C', True),
                      ('            END IF', False),
                      ('C', True),
                      ("C           Compute the UdU' or LdL' factorization.", True),
                      ('C           Workspace: need   1,', True),
                      ('C                      prefer M*NB.', True),
                      ('C', True),
                      ('            CALL DSYTRF( UPLO, M, R, LDR, IPIV, DWORK, LDWORK, INFO )', False),
                      ('            OUFACT = 2', False),
                      ('            IF( INFO.GT.0 ) THEN', False),
                      ('               DWORK(2) = ONE', False),
                      ('               RETURN', False),
                      ('            END IF', False),
                      ('            WRKOPT = MAX( WRKOPT, INT( DWORK(1) ) )', False),
                      ('C', True),
                      ('C           Compute the reciprocal of the condition number of R.', True),
                      ('C           Workspace: need 2*M.', True),
                      ('C', True),
                      ('            CALL DSYCON( UPLO, M, R, LDR, IPIV, RNORM, RCOND, DWORK,', False),
                      ('     $                   IWORK, INFO )', False),
                      ('C', True),
                      ('C           Return if the matrix is singular to working precision.', True),
                      ('C', True),
                      ('            DWORK(2) = RCOND', False),
                      ('            IF( RCOND.LT.EPS ) THEN', False),
                      ('               INFO = M + 1', False),
                      ('               RETURN', False),
                      ('            END IF', False),
                      ('         END IF', False),
                      ('      END IF', False),
                      ('C', True),
                      ('      IF (OUFACT.EQ.1 ) THEN', False),
                      ('C', True),
                      ('C        Solve positive definite linear system(s).', True),
                      ('C', True),
                      ('         IF ( LUPLOU ) THEN', False),
                      ("            TRANS = 'N'", False),
                      ('         ELSE', False),
                      ("            TRANS = 'T'", False),
                      ('         END IF', False),
                      ('C', True),
                      ('C        Solve the system X*U = B, overwriting B with X.', True),
                      ('C', True),
                      ("         CALL DTRSM( 'Right', UPLO, TRANS, 'Non-unit', N, M,", False),
                      ('     $               ONE, R, LDR, B, LDB )', False),
                      ('C', True),
                      ('         IF ( LJOBG ) THEN', False),
                      ('C                                      -1', True),
                      ("C           Compute the matrix  G = B*R  *B', multiplying X*X' in G.", True),
                      ('C', True),
                      ("            CALL DSYRK( UPLO, 'No transpose', N, M, ONE, B, LDB, ZERO,", False),
                      ('     $                  G, LDG )', False),
                      ('         END IF', False),
                      ('C', True),
                      ('         IF( LJOBL ) THEN', False),
                      ('C', True),
                      ('C           Update matrices A and Q.', True),
                      ('C', True),
                      ('C           Solve the system Y*U = L, overwriting L with Y.', True),
                      ('C', True),
                      ("            CALL DTRSM( 'Right', UPLO, TRANS, 'Non-unit', N, M,", False),
                      ('     $                  ONE, R, LDR, L, LDL )', False),
                      ('C', True),
                      ("C           Compute A <- A - X*Y'.", True),
                      ('C', True),
                      ("            CALL DGEMM( 'No transpose', 'Transpose', N, N, M, -ONE, B,", False),
                      ('     $                  LDB, L, LDL, ONE, A, LDA )', False),
                      ('C', True),
                      ("C           Compute Q <- Q - Y*Y'.", True),
                      ('C', True),
                      ("            CALL DSYRK( UPLO, 'No transpose', N, M, -ONE, L, LDL, ONE,", False),
                      ('     $                  Q, LDQ )', False),
                      ('         END IF', False),
                      ('      ELSE', False),
                      ('C', True),
                      ('C        Solve indefinite linear system(s).', True),
                      ('C', True),
                      ("C        Solve the system UdU'*X = B' (or LdL'*X = B').", True),
                      ('C        Workspace: need N*M.', True),
                      ('C', True),
                      ('         DO 100 J = 1, M', False),
                      ('            CALL DCOPY( N, B(1,J), 1, DWORK(J), M )', False),
                      ('  100    CONTINUE', False),
                      ('C', True),
                      ('         CALL DSYTRS( UPLO, M, N, R, LDR, IPIV, DWORK, M, INFO )', False),
                      ('C', True),
                      ('         IF ( LJOBG ) THEN', False),
                      ('C                                                    -1', True),
                      ("C           Compute a triangle of the matrix  G = B*R  *B' = B*X.", True),
                      ('C', True),
                      ('            IF ( LUPLOU ) THEN', False),
                      ('               I = 1', False),
                      ('C', True),
                      ('               DO 120 J = 1, N', False),
                      ("                  CALL DGEMV( 'No transpose', J, M, ONE, B, LDB,", False),
                      ('     $                        DWORK(I), 1, ZERO, G(1,J), 1 )', False),
                      ('                  I = I + M', False),
                      ('  120          CONTINUE', False),
                      ('C', True),
                      ('            ELSE', False),
                      ('C', True),
                      ('               DO 140 J = 1, N', False),
                      ("                  CALL DGEMV( 'Transpose', M, J, ONE, DWORK, M, B(J,1),", False),
                      ('     $                        LDB, ZERO, G(J,1), LDG )', False),
                      ('  140          CONTINUE', False),
                      ('C', True),
                      ('            END IF', False),
                      ('         END IF', False),
                      ('C', True),
                      ('         IF( LJOBL ) THEN', False),
                      ('C', True),
                      ('C           Update matrices A and Q.', True),
                      ('C', True),
                      ("C           Solve the system UdU'*Y = L' (or LdL'*Y = L').", True),
                      ('C', True),
                      ('            DO 160 J = 1, M', False),
                      ('               CALL DCOPY( N, L(1,J), 1, DWORK(J), M )', False),
                      ('  160       CONTINUE', False),
                      ('C', True),
                      ('            CALL DSYTRS( UPLO, M, N, R, LDR, IPIV, DWORK, M, INFO )', False),
                      ('C', True),
                      ('C           A <- A - B*Y.', True),
                      ('C', True),
                      ("            CALL DGEMM( 'No transpose', 'No transpose', N, N, M, -ONE,", False),
                      ('     $                  B, LDB, DWORK, M, ONE, A, LDA )', False),
                      ('C                                            -          -1', True),
                      ("C           Compute a triangle of the matrix Q = Q - L*R  *L' = Q - L*Y.", True),
                      ('C', True),
                      ('            IF ( LUPLOU ) THEN', False),
                      ('               I = 1', False),
                      ('C', True),
                      ('               DO 180 J = 1, N', False),
                      ("                  CALL DGEMV( 'No transpose', J, M, -ONE, L, LDL,", False),
                      ('     $                        DWORK(I), 1, ONE, Q(1,J), 1 )', False),
                      ('                  I = I + M', False),
                      ('  180          CONTINUE', False),
                      ('C', True),
                      ('            ELSE', False),
                      ('C', True),
                      ('               DO 200 J = 1, N', False),
                      ("                  CALL DGEMV( 'Transpose', M, J, -ONE, DWORK, M, L(J,1),", False),
                      ('     $                        LDL, ONE, Q(J,1), LDQ )', False),
                      ('  200          CONTINUE', False),
                      ('C', True),
                      ('            END IF', False),
                      ('         END IF', False),
                      ('      END IF', False),
                      ('C', True),
                      ('      DWORK(1) = WRKOPT', False),
                      ('      IF ( .NOT.LFACTA ) DWORK(2) = RCOND', False),
                      ('C', True),
                      ('C *** Last line of SB02MT ***', True),
                      ('      RETURN', False),
                      ('      END', False), }
        for fortran_line, expected in test_cases:
            result = f2pe.is_comment(fortran_line)
            self.assertEqual(result, expected)

    def test_fortran_filename_to_python_filename(self):
        fortran_filename = 'SB02MT.f'
        result = f2pe.fortran_filename_to_python_filename(fortran_filename)
        expected = 'sb02mt.py'
        self.assertEqual(result, expected)

if __name__ == '__main__':
    unittest.main()
