name: CI linux

on : [push]

jobs:
  build:
    name: Python ${{ matrix.python }} with TEST_CONDA=${{ matrix.test_conda }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python: [2.7, 3.6, 3.7]
        slycot: [slycot, '']
        scipy: [scipy, scipy==0.19.1]
        exclude:
          - python: 3.7
            slycot: ''
            scipy: scipy==0.19.1
    steps:
    - uses: actions/checkout@v1
    - name: before install
      env:
        SLYCOT: ${{ matrix.slycot }}
        PYTHON: ${{ matrix.python }}
      run: 
        source ./.github/workflows/before_install.sh
    - name: install
      env:
        SCIPY: ${{ matrix.scipy }}
        SLYCOT: ${{ matrix.slycot }}
      run: 
        source ./.github/workflows/install.sh
